joint_names: 
  - fl_caster_rotation_joint
  - fl_caster_l_wheel_joint
  - fl_caster_r_wheel_joint
  - fr_caster_rotation_joint
  - fr_caster_l_wheel_joint
  - fr_caster_r_wheel_joint
  - bl_caster_rotation_joint
  - bl_caster_l_wheel_joint
  - bl_caster_r_wheel_joint
  - br_caster_rotation_joint
  - br_caster_l_wheel_joint
  - br_caster_r_wheel_joint
  - torso_lift_joint
  - head_pan_joint
  - head_tilt_joint
  - laser_tilt_mount_joint
  - r_upper_arm_roll_joint
  - r_shoulder_pan_joint
  - r_shoulder_lift_joint
  - r_forearm_roll_joint
  - r_elbow_flex_joint
  - r_wrist_flex_joint
  - r_wrist_roll_joint
  - r_gripper_joint
  - r_gripper_l_finger_joint
  - r_gripper_r_finger_joint
  - r_gripper_r_finger_tip_joint
  - r_gripper_l_finger_tip_joint
  - l_upper_arm_roll_joint
  - l_shoulder_pan_joint
  - l_shoulder_lift_joint
  - l_forearm_roll_joint
  - l_elbow_flex_joint
  - l_wrist_flex_joint
  - l_wrist_roll_joint
  - l_gripper_joint
  - l_gripper_l_finger_joint
  - l_gripper_r_finger_joint
  - l_gripper_r_finger_tip_joint
  - l_gripper_l_finger_tip_joint
