# -----------------------------------------------------------------------------------
# Dynamic Movement Primitive (DMP)
# -----------------------------------------------------------------------------------

joint_space_dmp:

  # dmp parameters
  initial_time:
    tau: 2.0
    delta_t: 0.001
  execution_duration: 2.0
  teaching_duration: 2.0
  cutoff: 0.001  
  type: 1

  lwr:
    activation: 0.7
    exponentially_spaced: yes
    use_offset: no
    num_rfs: 20

  # canonical system parameters
  canonical_system_parameters:
    alpha_x: 0.01

  # transformation system parameters
  transformation_systems_parameters:
    -
      name: "R_SFE"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_SAA"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HR"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_EB"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_WR"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_WFE"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_WAA"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0

cartesian_space_dmp:

  # dmp parameters
  initial_time:
    tau: 2.0
    delta_t: 0.001
  execution_duration: 2.0
  teaching_duration: 2.0
  cutoff: 0.001
  type: 2

  lwr:
    activation: 0.7
    exponentially_spaced: yes
    use_offset: no
    num_rfs: 20

  # canonical system parameters
  canonical_system_parameters:
    alpha_x: 0.01

  # transformation system parameters
  transformation_systems_parameters:
    -
      name: "R_HAND_X"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_Y"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_Z"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QW"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QX"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QY"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QZ"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0

cartesian_and_joint_space_dmp:

  # dmp parameters
  initial_time:
    tau: 2.0
    delta_t: 0.001
  execution_duration: 2.0
  teaching_duration: 2.0
  cutoff: 0.001
  type: 3

  lwr:
    activation: 0.7
    exponentially_spaced: yes
    use_offset: no
    num_rfs: 20

  # canonical system parameters
  canonical_system_parameters:
    alpha_x: 0.01

  # transformation system parameters
  transformation_systems_parameters:
    -
      name: "R_HAND_X"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_Y"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_Z"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QW"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QX"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QY"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HAND_QZ"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_SFE"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_SAA"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_HR"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_EB"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_WR"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_WFE"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "R_WAA"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0

dmp:

  # dmp parameters
  initial_time:
    tau: 2.0
    delta_t: 0.001
  execution_duration: 2.0
  teaching_duration: 2.0
  cutoff: 0.001  
  type: 0

  lwr:
    activation: 0.7
    exponentially_spaced: yes
    use_offset: no
    num_rfs: 20

  # canonical system parameters
  canonical_system_parameters:
    alpha_x: 0.01

  # transformation system parameters
  transformation_systems_parameters:
    -
      name: "test_X"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "test_Y"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0
    -
      name: "test_Z"
      ICRA2009:
        k_gain: 50.0
      NC2010:
        k_gain: 10.0



