set(_CATKIN_CURRENT_PACKAGE "dynamic_movement_primitive")
set(dynamic_movement_primitive_VERSION "0.0.0")
set(dynamic_movement_primitive_MAINTAINER "robot <robot@todo.todo>")
set(dynamic_movement_primitive_PACKAGE_FORMAT "1")
set(dynamic_movement_primitive_BUILD_DEPENDS "roscpp" "usc_utilities" "message_generation" "cmake_modules" "rosbag" "sensor_msgs" "std_msgs")
set(dynamic_movement_primitive_BUILD_EXPORT_DEPENDS "roscpp" "usc_utilities" "message_runtime" "cmake_modules" "rosbag" "sensor_msgs" "std_msgs")
set(dynamic_movement_primitive_BUILDTOOL_DEPENDS "catkin")
set(dynamic_movement_primitive_BUILDTOOL_EXPORT_DEPENDS )
set(dynamic_movement_primitive_EXEC_DEPENDS "roscpp" "usc_utilities" "message_runtime" "cmake_modules" "rosbag" "sensor_msgs" "std_msgs")
set(dynamic_movement_primitive_RUN_DEPENDS "roscpp" "usc_utilities" "message_runtime" "cmake_modules" "rosbag" "sensor_msgs" "std_msgs")
set(dynamic_movement_primitive_TEST_DEPENDS )
set(dynamic_movement_primitive_DOC_DEPENDS )
set(dynamic_movement_primitive_DEPRECATED "")