l_arm_dmp_joint_position_controller:
  type: pr2_dynamic_movement_primitive_controller/DMPJointPositionController
  # which DMP formaulation is used (ICRA2009 vs. NC2010) 
  dmp_implementation: ICRA2009DMPControllerImplementation
  
