# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/CanonicalSystemMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/CanonicalSystemParametersMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/CanonicalSystemStateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/ControllerStatusMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/DMPUtilitiesMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/DynamicMovementPrimitiveMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/DynamicMovementPrimitiveParametersMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/DynamicMovementPrimitiveStateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010CanonicalSystemMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010CanonicalSystemParametersMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010CanonicalSystemStateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010DynamicMovementPrimitiveMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010DynamicMovementPrimitiveParametersMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010DynamicMovementPrimitiveStateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010TransformationSystemMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010TransformationSystemParametersMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/NC2010TransformationSystemStateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/Model.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/StateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/TimeMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/TransformationSystemMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/TransformationSystemParametersMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/TransformationSystemStateMsg.msg;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg/TypeMsg.msg"
services_str = ""
pkg_name = "dynamic_movement_primitive"
dependencies_str = "std_msgs;sensor_msgs"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "dynamic_movement_primitive;/home/yzheng/yzheng_ws/src/dmp/dynamic_movement_primitive/msg;std_msgs;/opt/ros/indigo/share/std_msgs/cmake/../msg;sensor_msgs;/opt/ros/indigo/share/sensor_msgs/cmake/../msg;geometry_msgs;/opt/ros/indigo/share/geometry_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/indigo/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
